### PR TITLE
Gradio Demo on Huggingface

### PR DESCRIPTION
**Pull request by AMEERAZAM08**
If you  wanted to anything in pipeline then please make change on https://huggingface.co/spaces/ameerazam08/InstantStyle-GPU-Demo

### CODE REVIEW

**Comment by AMEERAZAM08** [comment]
@ResearcherXman   Good works

**Comment by AMEERAZAM08** [comment]
https://huggingface.co/spaces/ameerazam08/InstantStyle-GPU-Demo
check the demo its runing on GPU at HF platform

**Comment by AMEERAZAM08** [comment]
@ResearcherXman Consider my contribution that will help me alot

**Comment by ResearcherXman** [comment]
Thanks, could you rename the folder name from gradio_src to gradio_demo, which is consistent with InstantID. @AMEERAZAM08

**Comment by AMEERAZAM08** [comment]
Sure

**Comment by AMEERAZAM08** [comment]
@ResearcherXman changes done as per mention

**Comment by AMEERAZAM08** [comment]
Thanks support in diffusers already there https://github.com/huggingface/diffusers/pull/7586
I started working on this part but thanks

**Pull request merged**
